# Generated by Django 5.1.5 on 2026-02-08 00:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this record was soft-deleted', null=True)),
                ('alert_type', models.CharField(choices=[('clabsi', 'CLABSI Detection'), ('ssi', 'SSI Detection'), ('cauti', 'CAUTI Detection'), ('vae', 'VAE Detection'), ('cdi', 'CDI Detection'), ('dosing_allergy', 'Dosing: Allergy Alert'), ('dosing_renal', 'Dosing: Renal Adjustment Needed'), ('dosing_age', 'Dosing: Age-Based Alert'), ('dosing_weight', 'Dosing: Weight-Based Alert'), ('dosing_interaction', 'Dosing: Drug Interaction'), ('dosing_route', 'Dosing: Route Alert'), ('dosing_indication', 'Dosing: Indication Mismatch'), ('dosing_duration', 'Dosing: Duration Alert'), ('dosing_extended_infusion', 'Dosing: Extended Infusion Recommended'), ('drug_bug_mismatch', 'Drug-Bug Mismatch'), ('culture_no_therapy', 'Culture Without Therapy'), ('abx_approval_needed', 'ABX Approval Needed'), ('abx_reapproval_needed', 'ABX Re-approval Needed'), ('guideline_adherence', 'Guideline Adherence Alert'), ('bundle_incomplete', 'Bundle Incomplete'), ('surgical_prophylaxis', 'Surgical Prophylaxis Alert'), ('mdro_detection', 'MDRO Detection'), ('outbreak_cluster', 'Outbreak Cluster Detected'), ('broad_spectrum_usage', 'Broad Spectrum Usage'), ('duplicate_therapy', 'Duplicate Therapy'), ('other', 'Other Alert')], db_index=True, help_text='Type of alert', max_length=50)),
                ('source_module', models.CharField(help_text="AEGIS module that generated this alert (e.g., 'hai_detection', 'dosing_verification')", max_length=100)),
                ('source_id', models.CharField(help_text='ID from source module (e.g., CLABSI candidate ID, dose alert ID)', max_length=255)),
                ('title', models.CharField(help_text='Alert title (short summary)', max_length=500)),
                ('summary', models.TextField(help_text='Brief summary of the alert')),
                ('details', models.JSONField(default=dict, help_text='Full alert details (structure varies by alert type)')),
                ('patient_id', models.CharField(blank=True, help_text='Patient ID from EHR', max_length=255, null=True)),
                ('patient_mrn', models.CharField(blank=True, db_index=True, help_text='Patient MRN', max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, help_text='Patient name (for display only)', max_length=255, null=True)),
                ('patient_location', models.CharField(blank=True, help_text='Patient location/unit', max_length=255, null=True)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical')], db_index=True, default='medium', help_text='Alert severity', max_length=20)),
                ('priority_score', models.IntegerField(default=50, help_text='Priority score (0-100, higher = more urgent)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('sent', 'Sent to Provider'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('snoozed', 'Snoozed'), ('resolved', 'Resolved'), ('expired', 'Expired')], db_index=True, default='pending', help_text='Current alert status', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When alert was sent to provider', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When alert was acknowledged', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, help_text='When alert was resolved', null=True)),
                ('resolution_reason', models.CharField(blank=True, choices=[('accepted', 'Recommendation Accepted'), ('already_addressed', 'Already Addressed'), ('clinically_inappropriate', 'Clinically Inappropriate'), ('patient_discharged', 'Patient Discharged'), ('patient_expired', 'Patient Expired'), ('false_positive', 'False Positive'), ('duplicate', 'Duplicate Alert'), ('auto_resolved', 'Auto-Resolved'), ('other', 'Other Reason')], help_text='Reason for resolution', max_length=50, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about resolution', null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, help_text='Alert snoozed until this time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the alert', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Alert expires at this time (auto-resolve)', null=True)),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether notification was sent')),
                ('notification_channels', models.JSONField(default=list, help_text='Channels where notification was sent (email, teams, sms)')),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='User who acknowledged the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('snoozed_by', models.ForeignKey(blank=True, help_text='User who snoozed the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snoozed_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('action', models.CharField(help_text='Action performed (created, acknowledged, resolved, snoozed, etc.)', max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('old_status', models.CharField(blank=True, help_text='Status before action', max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, help_text='Status after action', max_length=20, null=True)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of user who performed action', null=True)),
                ('alert', models.ForeignKey(help_text='Alert this audit entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='alerts.alert')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Audit Entry',
                'verbose_name_plural': 'Alert Audit Entries',
                'db_table': 'alert_audit',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'status'], name='alerts_alert_t_69ec1b_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['patient_mrn', 'status'], name='alerts_patient_e94e74_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', '-created_at'], name='alerts_severit_03a0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['source_module', 'source_id'], name='alerts_source__b5875f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='alerts_status_5c7524_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaudit',
            index=models.Index(fields=['alert', '-performed_at'], name='alert_audit_alert_i_17feca_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaudit',
            index=models.Index(fields=['performed_by', '-performed_at'], name='alert_audit_perform_aac044_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaudit',
            index=models.Index(fields=['action', '-performed_at'], name='alert_audit_action_c74ef9_idx'),
        ),
    ]
