# Generated by Django 5.1.5 on 2026-02-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("clabsi", "CLABSI Detection"),
                    ("ssi", "SSI Detection"),
                    ("cauti", "CAUTI Detection"),
                    ("vae", "VAE Detection"),
                    ("cdi", "CDI Detection"),
                    ("dosing_allergy", "Dosing: Allergy Alert"),
                    ("dosing_renal", "Dosing: Renal Adjustment Needed"),
                    ("dosing_age", "Dosing: Age-Based Alert"),
                    ("dosing_weight", "Dosing: Weight-Based Alert"),
                    ("dosing_interaction", "Dosing: Drug Interaction"),
                    ("dosing_route", "Dosing: Route Alert"),
                    ("dosing_indication", "Dosing: Indication Mismatch"),
                    ("dosing_duration", "Dosing: Duration Alert"),
                    (
                        "dosing_extended_infusion",
                        "Dosing: Extended Infusion Recommended",
                    ),
                    ("drug_bug_mismatch", "Drug-Bug Mismatch"),
                    ("culture_no_therapy", "Culture Without Therapy"),
                    ("abx_approval_needed", "ABX Approval Needed"),
                    ("abx_reapproval_needed", "ABX Re-approval Needed"),
                    ("guideline_adherence", "Guideline Adherence Alert"),
                    ("bundle_incomplete", "Bundle Incomplete"),
                    ("surgical_prophylaxis", "Surgical Prophylaxis Alert"),
                    ("mdro_detection", "MDRO Detection"),
                    ("outbreak_cluster", "Outbreak Cluster Detected"),
                    ("bacteremia", "Bacteremia Alert"),
                    ("broad_spectrum_usage", "Broad Spectrum Usage"),
                    ("duplicate_therapy", "Duplicate Therapy"),
                    ("other", "Other Alert"),
                ],
                db_index=True,
                help_text="Type of alert",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="resolution_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Recommendation Accepted"),
                    ("already_addressed", "Already Addressed"),
                    ("clinically_inappropriate", "Clinically Inappropriate"),
                    ("patient_discharged", "Patient Discharged"),
                    ("patient_expired", "Patient Expired"),
                    ("false_positive", "False Positive"),
                    ("duplicate", "Duplicate Alert"),
                    ("auto_resolved", "Auto-Resolved"),
                    ("messaged_team", "Messaged Team"),
                    ("discussed_with_team", "Discussed with Team"),
                    ("therapy_changed", "Therapy Changed"),
                    ("therapy_stopped", "Therapy Stopped"),
                    ("suggested_alternative", "Suggested Alternative"),
                    ("culture_pending", "Culture Pending"),
                    ("other", "Other Reason"),
                ],
                help_text="Reason for resolution",
                max_length=50,
                null=True,
            ),
        ),
    ]
