# Generated by Django 5.1.5 on 2026-02-08 00:15

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('asp_pharmacist', 'ASP Pharmacist'), ('infection_preventionist', 'Infection Preventionist'), ('physician', 'Physician'), ('admin', 'Administrator')], default='physician', help_text="User's primary role in AEGIS system", max_length=50)),
                ('department', models.CharField(blank=True, help_text="Department (e.g., 'Pharmacy', 'Infection Control')", max_length=255)),
                ('job_title', models.CharField(blank=True, help_text="Job title (e.g., 'Clinical Pharmacist', 'Physician')", max_length=255)),
                ('location', models.CharField(blank=True, help_text='Primary work location', max_length=255)),
                ('sso_id', models.CharField(blank=True, help_text="SSO provider's unique user ID (SAML NameID or LDAP DN)", max_length=255, null=True, unique=True)),
                ('ldap_dn', models.CharField(blank=True, help_text='LDAP Distinguished Name', max_length=500)),
                ('ad_groups', models.JSONField(blank=True, default=list, help_text='Active Directory groups (synced from LDAP)')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True)),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Count of consecutive failed login attempts')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text='Account locked until this time (after failed login attempts)', null=True)),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Receive email notifications for alerts')),
                ('teams_notifications_enabled', models.BooleanField(default=True, help_text='Receive Microsoft Teams notifications')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text="Unique permission identifier (e.g., 'dosing_verification.view_alerts')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows')),
                ('module', models.CharField(help_text='AEGIS module this permission belongs to', max_length=100)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'auth_permissions',
                'ordering': ['module', 'codename'],
                'indexes': [models.Index(fields=['module'], name='auth_permis_module_f5bccd_idx'), models.Index(fields=['codename'], name='auth_permis_codenam_c87527_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('asp_pharmacist', 'ASP Pharmacist'), ('infection_preventionist', 'Infection Preventionist'), ('physician', 'Physician'), ('admin', 'Administrator')], help_text='User role', max_length=50)),
                ('permission', models.ForeignKey(help_text='Permission granted to this role', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.permission')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
                'ordering': ['role', 'permission'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('login_method', models.CharField(choices=[('saml', 'SAML SSO'), ('ldap', 'LDAP'), ('local', 'Local Password')], default='saml', help_text='Authentication method used', max_length=50)),
                ('login_time', models.DateTimeField(auto_now_add=True, help_text='When the user logged in')),
                ('logout_time', models.DateTimeField(blank=True, help_text='When the user logged out (null if still active)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active')),
                ('user', models.ForeignKey(help_text='User who created this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='auth_user_role_f90fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['sso_id'], name='auth_user_sso_id_6a6157_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department'], name='auth_user_departm_266905_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-login_time'], name='user_sessio_user_id_d40ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='user_sessio_session_cc84b9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active', '-login_time'], name='user_sessio_is_acti_5ea524_idx'),
        ),
    ]
