# Generated by Django 5.1.5 on 2026-02-08 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_alerts', models.IntegerField(default=0)),
                ('alerts_by_type', models.JSONField(default=dict)),
                ('alerts_by_severity', models.JSONField(default=dict)),
                ('total_actions', models.IntegerField(default=0)),
                ('actions_by_module', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'daily_snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProviderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('action_type', models.CharField(help_text='Type of action', max_length=100)),
                ('module', models.CharField(help_text='AEGIS module', max_length=100)),
                ('patient_mrn', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(default=dict)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='provider_ac_user_id_7ff538_idx'), models.Index(fields=['module', '-created_at'], name='provider_ac_module_227b84_idx')],
            },
        ),
    ]
